import type { Metadata } from "next";
import { Theme, ThemePanel } from "@radix-ui/themes";
import "./globals.css";
import Navbar from "./Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className="bg-slate-50">
        <Theme>
          <div className="font-roboto">
            <Navbar />
            <main className="my-6">{children}</main>
          </div>
          {/* <ThemePanel /> */}
        </Theme>
      </body>
    </html>
  );
}
